#!/bin/bash

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check availability :
if [ cpufreq-set ]
then
	echo ""
else
	echo -e "${RED} [ERROR] cpufreq-set not found. Try installing... ${NC} \n"
	echo "`sudo apt install cpufrequtils`"
fi

# Count CPUs :
MAX_CPU=$((`nproc --all` - 1))
CPU_FOUND=$((MAX_CPU + 1))
echo -e "${YELLOW} [INFO] Found ${CPU_FOUND} CPUs.\n" 
MIN="400Mhz"
MAX="600Mhz"
P_MAX="5500Mhz"

# Set everything in range [400~600] Mhz first &&
# Set 2 first cores as "P-core" within max range : 
for i in $(seq 0 $MAX_CPU); do
  [[ $i -lt 2 ]] && MAX_OPTION=$P_MAX || MAX_OPTION=$MAX
  echo -e "${GREEN} [cpufreq-set]: CPU #" $i " >> [" $MIN "~" $MAX_OPTION "]${NC}";
	sudo cpufreq-set -c $i --min $MIN --max $MAX_OPTION;
done


